-- ==========================================
-- SQL MIGRATION FOR C-PRESENCE KCI REVISIONS
-- Copy and run these queries in your Supabase SQL Editor
-- ==========================================

-- 1. Update users table with Dinasaan start and end times
ALTER TABLE users ADD COLUMN IF NOT EXISTS dinasan_start_time TIME;
ALTER TABLE users ADD COLUMN IF NOT EXISTS dinasan_end_time TIME;

-- 2. Update attendance table with SLA calculation columns
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS nilai_awal_dinas NUMERIC DEFAULT 0;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS nilai_akhir_dinas NUMERIC DEFAULT 0;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS sla_harian NUMERIC DEFAULT 0;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS is_dinas_luar BOOLEAN DEFAULT FALSE;

-- 3. Update stations table to support custom radius per station
ALTER TABLE stations ADD COLUMN IF NOT EXISTS radius_meters INTEGER DEFAULT 600;

-- 4. Migrate and unify attachment/dokumentasi columns in approval_requests table
-- Copy any existing data from attachment_url to lampiran_dokumentasi_url
UPDATE approval_requests 
SET lampiran_dokumentasi_url = attachment_url 
WHERE lampiran_dokumentasi_url IS NULL AND attachment_url IS NOT NULL;

-- Drop the redundant attachment_url column
ALTER TABLE approval_requests DROP COLUMN IF EXISTS attachment_url;

-- 5. Add is_read column to notifications table
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT FALSE;

-- 6. Create storage buckets and enable public access + RLS policies
-- Note: Run this to automatically create the buckets and allow anyone to upload/read files.

-- Create 'dinas-luar-evidence' bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('dinas-luar-evidence', 'dinas-luar-evidence', true)
ON CONFLICT (id) DO NOTHING;

-- Create 'sop_documents' bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('sop_documents', 'sop_documents', true)
ON CONFLICT (id) DO NOTHING;

-- Enable RLS Policies for 'dinas-luar-evidence' (Allow all actions for public)
CREATE POLICY "Allow public access to dinas-luar-evidence"
ON storage.objects FOR ALL
TO public
USING (bucket_id = 'dinas-luar-evidence')
WITH CHECK (bucket_id = 'dinas-luar-evidence');

-- Enable RLS Policies for 'sop_documents' (Allow all actions for public)
CREATE POLICY "Allow public access to sop_documents"
ON storage.objects FOR ALL
TO public
USING (bucket_id = 'sop_documents')
WITH CHECK (bucket_id = 'sop_documents');

-- 7. Add approved_by_name column to approval_requests to save supervisor name
ALTER TABLE approval_requests ADD COLUMN IF NOT EXISTS approved_by_name TEXT;

-- 8. Allow public read access to sop_documents table (fixing empty data issue due to RLS)
ALTER TABLE IF EXISTS public.sop_documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to sop_documents table" ON public.sop_documents;
CREATE POLICY "Allow public read access to sop_documents table"
ON public.sop_documents FOR SELECT
TO public
USING (true);

-- 9. (Removed) Add employee_id column is no longer needed because users.id (UUID) is generated by Supabase.

-- 10. Drop phone_number column from users table
ALTER TABLE public.users DROP COLUMN IF EXISTS phone_number;


